import 'dotenv/config'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

type ExerciseSeed = {
  name: string
  movement_pattern: 'squat' | 'hinge' | 'push' | 'pull' | 'carry' | 'core'
  stimulus_tags: string[]
  contraindications: string[]
  safety_flags: string[]
  equipment: string[]
  intensity_band: 'low' | 'medium' | 'high'
  experience_level: 'beginner' | 'intermediate' | 'advanced'
  tier: 1 | 2 | 3
  swap_group_id: string
}

const exercises: ExerciseSeed[] = [
  {
    name: 'Back Squat',
    movement_pattern: 'squat',
    stimulus_tags: ['quads', 'glutes', 'core'],
    contraindications: ['knee_pain', 'lower_back_pain'],
    safety_flags: ['high_impact', 'deep_knee_flexion', 'low_back_load'],
    equipment: ['barbell', 'rack'],
    intensity_band: 'high',
    experience_level: 'beginner',
    tier: 1,
    swap_group_id: 'squat_primary',
  },
  {
    name: 'Bench Press',
    movement_pattern: 'push',
    stimulus_tags: ['chest', 'triceps', 'shoulders'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['barbell', 'bench', 'rack'],
    intensity_band: 'high',
    experience_level: 'beginner',
    tier: 1,
    swap_group_id: 'horizontal_push_primary',
  },
  {
    name: 'Deadlift',
    movement_pattern: 'hinge',
    stimulus_tags: ['hamstrings', 'glutes', 'back', 'traps'],
    contraindications: ['lower_back_pain'],
    safety_flags: ['low_back_load', 'high_impact'],
    equipment: ['barbell'],
    intensity_band: 'high',
    experience_level: 'beginner',
    tier: 1,
    swap_group_id: 'hinge_primary',
  },
  {
    name: 'Overhead Press',
    movement_pattern: 'push',
    stimulus_tags: ['shoulders', 'triceps', 'upper_traps'],
    contraindications: ['shoulder_pain', 'neck_pain'],
    safety_flags: ['shoulder_load', 'overhead_load'],
    equipment: ['barbell', 'rack'],
    intensity_band: 'high',
    experience_level: 'beginner',
    tier: 1,
    swap_group_id: 'vertical_push_primary',
  },
  {
    name: 'Barbell Row',
    movement_pattern: 'pull',
    stimulus_tags: ['back', 'biceps', 'rear_delts'],
    contraindications: ['lower_back_pain'],
    safety_flags: ['low_back_load'],
    equipment: ['barbell'],
    intensity_band: 'high',
    experience_level: 'beginner',
    tier: 1,
    swap_group_id: 'horizontal_pull_primary',
  },
  {
    name: 'Pull Up',
    movement_pattern: 'pull',
    stimulus_tags: ['back', 'biceps', 'core'],
    contraindications: ['shoulder_pain', 'elbow_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['pull_up_bar'],
    intensity_band: 'high',
    experience_level: 'intermediate',
    tier: 1,
    swap_group_id: 'vertical_pull_primary',
  },
  {
    name: 'Dumbbell Bench Press',
    movement_pattern: 'push',
    stimulus_tags: ['chest', 'triceps', 'shoulders'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['dumbbells', 'bench'],
    intensity_band: 'high',
    experience_level: 'beginner',
    tier: 1,
    swap_group_id: 'horizontal_push_primary',
  },
  {
    name: 'Bulgarian Split Squat',
    movement_pattern: 'squat',
    stimulus_tags: ['quads', 'glutes', 'hamstrings'],
    contraindications: ['knee_pain'],
    safety_flags: ['high_impact', 'deep_knee_flexion'],
    equipment: ['dumbbells', 'bench'],
    intensity_band: 'high',
    experience_level: 'intermediate',
    tier: 1,
    swap_group_id: 'squat_primary',
  },
  {
    name: 'Hack Squat',
    movement_pattern: 'squat',
    stimulus_tags: ['quads', 'glutes'],
    contraindications: ['knee_pain'],
    safety_flags: ['high_impact', 'deep_knee_flexion'],
    equipment: ['hack_squat_machine'],
    intensity_band: 'high',
    experience_level: 'beginner',
    tier: 1,
    swap_group_id: 'squat_primary',
  },
  {
    name: 'Front Squat',
    movement_pattern: 'squat',
    stimulus_tags: ['quads', 'core', 'upper_back'],
    contraindications: ['knee_pain', 'wrist_pain'],
    safety_flags: ['high_impact', 'deep_knee_flexion', 'wrist_load'],
    equipment: ['barbell', 'rack'],
    intensity_band: 'high',
    experience_level: 'advanced',
    tier: 1,
    swap_group_id: 'squat_primary',
  },
  {
    name: 'Close Grip Bench Press',
    movement_pattern: 'push',
    stimulus_tags: ['triceps', 'chest'],
    contraindications: ['elbow_pain', 'wrist_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['barbell', 'bench', 'rack'],
    intensity_band: 'high',
    experience_level: 'intermediate',
    tier: 1,
    swap_group_id: 'horizontal_push_primary',
  },
  {
    name: 'Incline Press',
    movement_pattern: 'push',
    stimulus_tags: ['upper_chest', 'triceps', 'front_delts'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['barbell', 'incline_bench', 'rack'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'incline_push',
  },
  {
    name: 'Dumbbell Incline Press',
    movement_pattern: 'push',
    stimulus_tags: ['upper_chest', 'triceps'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['dumbbells', 'incline_bench'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'incline_push',
  },
  {
    name: 'Dips',
    movement_pattern: 'push',
    stimulus_tags: ['chest', 'triceps', 'front_delts'],
    contraindications: ['shoulder_pain', 'elbow_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['dip_bars'],
    intensity_band: 'medium',
    experience_level: 'intermediate',
    tier: 2,
    swap_group_id: 'incline_push',
  },
  {
    name: 'Dumbbell Shoulder Press',
    movement_pattern: 'push',
    stimulus_tags: ['shoulders', 'triceps'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load', 'overhead_load'],
    equipment: ['dumbbells'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'vertical_push_secondary',
  },
  {
    name: 'Lat Pulldown',
    movement_pattern: 'pull',
    stimulus_tags: ['lats', 'biceps'],
    contraindications: [],
    safety_flags: [],
    equipment: ['cable_machine'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'vertical_pull_secondary',
  },
  {
    name: 'Seated Cable Row',
    movement_pattern: 'pull',
    stimulus_tags: ['mid_back', 'biceps', 'rear_delts'],
    contraindications: ['lower_back_pain'],
    safety_flags: ['low_back_load'],
    equipment: ['cable_machine'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'horizontal_pull_secondary',
  },
  {
    name: 'Dumbbell Row',
    movement_pattern: 'pull',
    stimulus_tags: ['lats', 'mid_back', 'biceps'],
    contraindications: [],
    safety_flags: [],
    equipment: ['dumbbells', 'bench'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'horizontal_pull_secondary',
  },
  {
    name: 'T-Bar Row',
    movement_pattern: 'pull',
    stimulus_tags: ['mid_back', 'lats', 'biceps'],
    contraindications: ['lower_back_pain'],
    safety_flags: ['low_back_load'],
    equipment: ['barbell', 't_bar_attachment'],
    intensity_band: 'medium',
    experience_level: 'intermediate',
    tier: 2,
    swap_group_id: 'horizontal_pull_secondary',
  },
  {
    name: 'Chin Up',
    movement_pattern: 'pull',
    stimulus_tags: ['lats', 'biceps'],
    contraindications: ['shoulder_pain', 'elbow_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['pull_up_bar'],
    intensity_band: 'medium',
    experience_level: 'intermediate',
    tier: 2,
    swap_group_id: 'vertical_pull_secondary',
  },
  {
    name: 'Romanian Deadlift',
    movement_pattern: 'hinge',
    stimulus_tags: ['hamstrings', 'glutes', 'lower_back'],
    contraindications: ['lower_back_pain', 'hamstring_injury'],
    safety_flags: ['low_back_load'],
    equipment: ['barbell'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'hinge_secondary',
  },
  {
    name: 'Leg Press',
    movement_pattern: 'squat',
    stimulus_tags: ['quads', 'glutes'],
    contraindications: ['knee_pain'],
    safety_flags: ['deep_knee_flexion'],
    equipment: ['leg_press_machine'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'squat_secondary',
  },
  {
    name: 'Hip Thrust',
    movement_pattern: 'hinge',
    stimulus_tags: ['glutes', 'hamstrings'],
    contraindications: [],
    safety_flags: [],
    equipment: ['barbell', 'bench'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'hinge_secondary',
  },
  {
    name: 'Walking Lunges',
    movement_pattern: 'squat',
    stimulus_tags: ['quads', 'glutes', 'hamstrings'],
    contraindications: ['knee_pain'],
    safety_flags: ['high_impact', 'deep_knee_flexion'],
    equipment: ['dumbbells'],
    intensity_band: 'medium',
    experience_level: 'beginner',
    tier: 2,
    swap_group_id: 'squat_secondary',
  },
  {
    name: 'Triceps Pushdown',
    movement_pattern: 'push',
    stimulus_tags: ['triceps'],
    contraindications: ['elbow_pain'],
    safety_flags: [],
    equipment: ['cable_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'triceps_isolation',
  },
  {
    name: 'Lateral Raise',
    movement_pattern: 'push',
    stimulus_tags: ['lateral_delts'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['dumbbells'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'delt_isolation',
  },
  {
    name: 'Cable Chest Fly',
    movement_pattern: 'push',
    stimulus_tags: ['chest', 'front_delts'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['cable_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'chest_isolation',
  },
  {
    name: 'Pec Deck Machine',
    movement_pattern: 'push',
    stimulus_tags: ['chest'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['pec_deck_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'chest_isolation',
  },
  {
    name: 'Skullcrushers',
    movement_pattern: 'push',
    stimulus_tags: ['triceps'],
    contraindications: ['elbow_pain'],
    safety_flags: [],
    equipment: ['barbell', 'bench'],
    intensity_band: 'low',
    experience_level: 'intermediate',
    tier: 3,
    swap_group_id: 'triceps_isolation',
  },
  {
    name: 'Overhead Triceps Extension',
    movement_pattern: 'push',
    stimulus_tags: ['triceps'],
    contraindications: ['elbow_pain', 'shoulder_pain'],
    safety_flags: ['overhead_load'],
    equipment: ['dumbbells'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'triceps_isolation',
  },
  {
    name: 'Front Raise',
    movement_pattern: 'push',
    stimulus_tags: ['front_delts'],
    contraindications: ['shoulder_pain'],
    safety_flags: ['shoulder_load'],
    equipment: ['dumbbells'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'delt_isolation',
  },
  {
    name: 'Biceps Curl',
    movement_pattern: 'pull',
    stimulus_tags: ['biceps'],
    contraindications: ['elbow_pain'],
    safety_flags: [],
    equipment: ['barbell'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'biceps_isolation',
  },
  {
    name: 'Hammer Curl',
    movement_pattern: 'pull',
    stimulus_tags: ['biceps', 'brachialis'],
    contraindications: ['elbow_pain'],
    safety_flags: [],
    equipment: ['dumbbells'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'biceps_isolation',
  },
  {
    name: 'Preacher Curl',
    movement_pattern: 'pull',
    stimulus_tags: ['biceps'],
    contraindications: ['elbow_pain'],
    safety_flags: [],
    equipment: ['barbell', 'preacher_bench'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'biceps_isolation',
  },
  {
    name: 'Reverse Curl',
    movement_pattern: 'pull',
    stimulus_tags: ['brachialis', 'forearms'],
    contraindications: ['elbow_pain', 'wrist_pain'],
    safety_flags: [],
    equipment: ['barbell'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'biceps_isolation',
  },
  {
    name: 'Rear Delt Fly',
    movement_pattern: 'pull',
    stimulus_tags: ['rear_delts', 'upper_back'],
    contraindications: ['shoulder_pain'],
    safety_flags: [],
    equipment: ['dumbbells'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'rear_delt_isolation',
  },
  {
    name: 'Barbell Shrug',
    movement_pattern: 'pull',
    stimulus_tags: ['traps'],
    contraindications: ['neck_pain'],
    safety_flags: ['neck_load'],
    equipment: ['barbell'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'trap_isolation',
  },
  {
    name: 'Face Pull',
    movement_pattern: 'pull',
    stimulus_tags: ['rear_delts', 'rotator_cuff'],
    contraindications: [],
    safety_flags: [],
    equipment: ['cable_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'rear_delt_isolation',
  },
  {
    name: 'Leg Extension',
    movement_pattern: 'squat',
    stimulus_tags: ['quads'],
    contraindications: ['knee_pain'],
    safety_flags: ['knee_shear'],
    equipment: ['leg_extension_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'quad_isolation',
  },
  {
    name: 'Seated Leg Curl',
    movement_pattern: 'hinge',
    stimulus_tags: ['hamstrings'],
    contraindications: ['hamstring_injury'],
    safety_flags: [],
    equipment: ['leg_curl_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'hamstring_isolation',
  },
  {
    name: 'Lying Leg Curl',
    movement_pattern: 'hinge',
    stimulus_tags: ['hamstrings'],
    contraindications: ['hamstring_injury'],
    safety_flags: [],
    equipment: ['leg_curl_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'hamstring_isolation',
  },
  {
    name: 'Standing Calf Raise',
    movement_pattern: 'carry',
    stimulus_tags: ['calves'],
    contraindications: ['achilles_injury'],
    safety_flags: [],
    equipment: ['calf_raise_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'calf_isolation',
  },
  {
    name: 'Seated Calf Raise',
    movement_pattern: 'carry',
    stimulus_tags: ['soleus'],
    contraindications: ['achilles_injury'],
    safety_flags: [],
    equipment: ['seated_calf_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'calf_isolation',
  },
  {
    name: 'Cable Crunch',
    movement_pattern: 'core',
    stimulus_tags: ['abs'],
    contraindications: ['lower_back_pain'],
    safety_flags: ['low_back_load'],
    equipment: ['cable_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'core_flexion',
  },
  {
    name: 'Hanging Leg Raise',
    movement_pattern: 'core',
    stimulus_tags: ['abs', 'hip_flexors'],
    contraindications: ['lower_back_pain', 'shoulder_pain'],
    safety_flags: ['low_back_load'],
    equipment: ['pull_up_bar'],
    intensity_band: 'low',
    experience_level: 'intermediate',
    tier: 3,
    swap_group_id: 'core_flexion',
  },
  {
    name: 'Plank',
    movement_pattern: 'core',
    stimulus_tags: ['core', 'glutes'],
    contraindications: ['wrist_pain'],
    safety_flags: [],
    equipment: [],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'core_stability',
  },
  {
    name: 'Ab Wheel Rollout',
    movement_pattern: 'core',
    stimulus_tags: ['abs', 'lats'],
    contraindications: ['lower_back_pain'],
    safety_flags: ['low_back_load'],
    equipment: ['ab_wheel'],
    intensity_band: 'low',
    experience_level: 'intermediate',
    tier: 3,
    swap_group_id: 'core_stability',
  },
  {
    name: 'Russian Twist',
    movement_pattern: 'core',
    stimulus_tags: ['obliques'],
    contraindications: ['lower_back_pain'],
    safety_flags: ['low_back_load'],
    equipment: [],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'core_rotation',
  },
  {
    name: 'Band Pull-Apart',
    movement_pattern: 'pull',
    stimulus_tags: ['rear_delts', 'rotator_cuff'],
    contraindications: [],
    safety_flags: [],
    equipment: ['resistance_band'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'shoulder_prehab',
  },
  {
    name: 'External Rotation',
    movement_pattern: 'pull',
    stimulus_tags: ['rotator_cuff'],
    contraindications: [],
    safety_flags: [],
    equipment: ['resistance_band', 'cable_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'shoulder_prehab',
  },
  {
    name: 'Pallof Press',
    movement_pattern: 'core',
    stimulus_tags: ['core', 'obliques'],
    contraindications: [],
    safety_flags: [],
    equipment: ['cable_machine'],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'core_stability',
  },
  {
    name: 'Glute Bridge',
    movement_pattern: 'hinge',
    stimulus_tags: ['glutes', 'hamstrings'],
    contraindications: [],
    safety_flags: [],
    equipment: [],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'hinge_prehab',
  },
  {
    name: 'Bird Dog',
    movement_pattern: 'core',
    stimulus_tags: ['core', 'glutes'],
    contraindications: [],
    safety_flags: [],
    equipment: [],
    intensity_band: 'low',
    experience_level: 'beginner',
    tier: 3,
    swap_group_id: 'core_stability',
  },
]

async function seedExercises() {
  const { error } = await supabase.from('exercises').insert(exercises)
  if (error) throw error
  console.log(`Seeded ${exercises.length} exercises`)
}

seedExercises().catch((err) => { console.error(err); process.exit(1) })
